/*
 * MTIMER0_config.h
 *
 *  Created on: Jun 11, 2023
 *      Author: elray
 */

#ifndef TIMER0_MTIMER0_CONFIG_H_
#define TIMER0_MTIMER0_CONFIG_H_
/*
 *
 * please configure timer clock :
 *
 * MTIMER_NO_CLK
 * MTIMER0_PRESCALER_1
 * MTIMER0_PRESCALER_8
 * MTIMER0_PRESCALER_64
 * MTIMER0_PRESCALER_256
 * MTIMER0_PRESCALER_1024
 * MTIMER_EXTCLK_FALL_EDGE
 * MTIMER_EXTCLK_RAIS_EDGE
 */

#define MTIMER0_CLK  MTIMER0_PRESCALER_256  //least timer

/*
 * please configute timer mode
 * MTIMER0_MODE_NORMAL
 MTIMER0_MODE_CTC

MTIMER0_MODE_FAST_PWM
 MTIMER0_PHASE_CORRECT_PWM
 *
 *
 */

#define MTIMER0_MODE MTIMER0_MODE_FAST_PWM
/*
	plese configure  OC0 MODE
	wave generation moe
 MTIMER_OC0_DISCONNECTED
 MTIMER_OC0_TOGGLE
 MTIMER_OC0_CLEAR
 MTIMER_OC0_SET

 MTIMER_OC0_INVERTED
 MTIMER_OC0_NONINVERTED
*/

#define MTIMER0_OC0_MODE MTIMER_OC0_INVERTED


#define FCPU 	16UL  //16 mega Hz

#endif /* TIMER0_MTIMER0_CONFIG_H_ */
